import { mission, suppliers, supplierIds, desiredOffers, invokePolicy, rankOffers } from './domain.js';
import { hasWebMCP, executeTool, getToolsFromSuppliers } from './webmcp.js';

const app=document.querySelector('#app');
const workflowStates=['IDLE','DISCOVERING','QUOTING','NEGOTIATING','COMPARING','AWAITING_APPROVAL','APPROVED','ORDERED'];
let workflow='IDLE',busy=false,orchestrating=false,audit=[];
let market=Object.fromEntries(supplierIds.map(id=>[id,{supplierId:id,status:'idle'}]));
const configured=window.OPENDEAL_CONFIG?.supplierUrls||window.OPENDEAL_SUPPLIER_URLS||{};
const supplierUrls={
 alpha:configured.alpha||'/supplier/alpha/',
 bravo:configured.bravo||'/supplier/bravo/',
 charlie:configured.charlie||'/supplier/charlie/'
};
const buyerOrigin=location.origin;
for(const id of supplierIds){const u=new URL(supplierUrls[id],location.href);if(u.origin!==location.origin)u.searchParams.set('buyerOrigin',buyerOrigin);supplierUrls[id]=u.href;}
const webmcp=hasWebMCP();
const iframeHost=document.querySelector('#supplier-iframes');
iframeHost.innerHTML=supplierIds.map(id=>`<iframe data-id="${id}" allow="tools" src="${supplierUrls[id]}" title="${suppliers[id].name} tool context"></iframe>`).join('');
const delay=(ms)=>new Promise(r=>setTimeout(r,ms));
const money=(n)=>Number.isFinite(n)?`$${Number(n).toLocaleString()}`:'—';
const esc=(s)=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function log(entry){audit.push({id:crypto.randomUUID(),at:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),...entry});render();}
function source(){return webmcp?'WebMCP':'Demo Orchestrator';}
function statusClass(row){return row.eligible===false?'bad':row.eligible?'good':'';}
function constraintText(row){return row.eligible===false?'✕ FAIL':row.eligible?'✓ PASS':'○ PENDING';}
function render(){
 const idx=workflowStates.indexOf(workflow);
 const marketCards=supplierIds.map(id=>{const p=suppliers[id],m=market[id],total=m.negotiated??m.quote;return `<article class="supplier-card ${['winner','ordered'].includes(m.status)?'winner':''}"><div class="supplier-id"><div class="supplier-monogram">${p.accent}</div><div><strong>${esc(p.name)}</strong><span>${p.inventory} units seeded</span></div></div><div class="supplier-metrics"><div><span>Total</span><strong>${money(total)}</strong></div><div><span>Delivery</span><strong>${esc(m.delivery??'—')}</strong></div><div><span>Constraint</span><strong class="${statusClass(m)}">${constraintText(m)}</strong></div></div><div class="supplier-rationale">${esc(m.rationale??'Awaiting agent discovery.')}</div></article>`}).join('');
 const ledger=audit.length?audit.slice().reverse().map(e=>`<div class="ledger-row"><div class="source-dot ${e.source==='Human'?'human':''}"></div><div class="ledger-main"><div class="ledger-top"><strong>${esc(e.tool??e.source)}</strong><span>${esc(e.at)}</span></div><p>${esc(e.summary)}</p>${e.policy?`<small>${esc(e.policy)}</small>`:''}</div><span class="source-tag">${esc(e.source)}</span></div>`).join(''):`<div class="empty-ledger"><span>⌁</span><p>No actions executed.</p></div>`;
 const cta=workflow==='IDLE'?`<button id="run" class="primary-btn">▶ Run agent mission</button>`:workflow==='AWAITING_APPROVAL'?`<button id="approve" class="approval-btn">✓ Approve $2,325</button>`:workflow==='ORDERED'?`<button id="reset" class="secondary-btn">↻ Reset demo</button>`:'';
 app.innerHTML=`<header class="topbar"><div class="brand"><div class="brand-mark">OD</div><div><strong>OPENDEAL</strong><span>Agent-native negotiation for the open web.</span></div></div><div class="topbar-actions"><span class="status-pill ${webmcp?'active':'fallback'}">${webmcp?'WebMCP: ACTIVE':'WebMCP: FALLBACK DEMO'}</span><span class="challenge-badge">WEBMCP CHALLENGE · 2026</span></div></header><main class="dashboard"><section class="hero-row"><div><span class="eyebrow">BOUNDED AUTHORITY · STRUCTURED NEGOTIATION · HUMAN CONTROL</span><h1>One mission. Three independent suppliers. One accountable decision.</h1></div><div class="hero-actions">${cta}</div></section><div class="state-rail">${workflowStates.map((s,i)=>`<div class="state-node ${i<idx?'done':''} ${i===idx?'current':''}"><span>${i<idx?'✓':i+1}</span><small>${s.replaceAll('_',' ')}</small></div>`).join('')}</div><div class="main-grid">
 <section class="panel mission-panel"><div class="panel-heading"><div><span class="eyebrow">BUYER MISSION</span><h2>Safety procurement</h2></div><span>◈</span></div>${[['Quantity','100'],['Specification','ANSI Z89.1 Type II'],['Hard deadline','Friday'],['Maximum spend','$2,500'],['Substitutions','Not allowed']].map(([a,b])=>`<div class="mission-stat"><span>${a}</span><strong>${b}</strong></div>`).join('')}<div class="savings-box"><span>◉</span><div><span>Realized savings</span><strong>${workflow==='ORDERED'?'$175':'—'}</strong></div></div></section>
 <section class="panel market-panel"><div class="panel-heading"><div><span class="eyebrow">LIVE MARKET</span><h2>Supplier field</h2></div><span class="live-dot">LIVE</span></div><div class="market-list">${marketCards}</div></section>
 <section class="panel contract-panel"><div class="panel-heading"><div><span class="eyebrow">AGENT CONTRACT</span><h2>OD-1047</h2></div><span>⬡</span></div><p class="contract-objective">Procure 100 ANSI Z89.1 Type II safety helmets</p><div class="contract-grid"><div><span class="section-label">Constraints</span>${['Total cost ≤ $2,500','Delivery no later than Friday','No substitutions','Explicit human approval for financial commitment'].map(x=>`<div class="check-row"><span>✓</span>${x}</div>`).join('')}</div><div><span class="section-label">Authorized before approval</span>${['Search inventory','Inspect specs','Request quotes','Negotiate','Check delivery'].map(x=>`<div class="capability-row">${x}<span>ALLOWED</span></div>`).join('')}</div></div><div class="financial-lock"><span>Financial commitment</span><strong>HUMAN LOCKED</strong></div></section>
 <section class="panel audit-panel"><div class="panel-heading"><div><span class="eyebrow">AGENT ACTIVITY</span><h2>Execution ledger</h2></div><span>≋</span></div><div class="ledger">${ledger}</div></section>
 <section class="panel inspector-panel"><div class="panel-heading"><div><span class="eyebrow">WEBMCP INSPECTOR</span><h2 id="inspector-title">${webmcp?'Inspecting real tools…':'Fallback environment'}</h2></div><button id="refresh-tools" class="icon-btn">↻</button></div><div id="tool-list">${webmcp?'<p class="muted">Waiting for supplier iframe tools…</p>':'<div class="fallback-box"><strong>Not simulated as active.</strong><p>This inspector only shows actual tools when <code>document.modelContext</code> exists.</p></div>'}</div></section>
 <section class="panel authority-panel"><div class="panel-heading"><div><span class="eyebrow">AGENT AUTHORITY</span><h2>Delegation policy</h2></div><span>⌾</span></div><div class="authority-row"><span>Search & compare</span><b class="allow">AUTONOMOUS</b></div><div class="authority-row"><span>Negotiate price</span><b class="allow">AUTONOMOUS</b></div><div class="authority-row"><span>Maximum spend</span><b>$2,500</b></div><div class="authority-row"><span>Final purchase</span><b class="${['APPROVED','ORDERED'].includes(workflow)?'allow':'locked'}">${['APPROVED','ORDERED'].includes(workflow)?'APPROVED':'HUMAN LOCK'}</b></div><div class="authority-note"><span>✦</span><p>The capability surface changes with authority. The purchase tool is not registered before approval.</p></div></section></div>
 ${workflow==='ORDERED'?'<section class="order-banner"><div><span class="eyebrow">PURCHASE ORDER CONFIRMED</span><h2>OD-1047 · Bravo Safety Supply</h2><p>100 ANSI Z89.1 Type II helmets · Friday delivery</p></div><div class="order-amount"><span>Total</span><strong>$2,325</strong><small>$175 under budget</small></div></section>':''}
 <button id="tech-toggle" class="technical-toggle"><span>Technical implementation</span><span>⌄</span></button><section id="tech-panel" class="technical-panel hidden"><p><strong>API:</strong> current draft uses <code>document.modelContext</code>.</p><p><strong>Composition:</strong> supplier routes are iframe-ready and configurable to distinct origins.</p><p><strong>Dynamic lifecycle:</strong> <code>AbortController</code> removes the one-time purchase capability after execution; order-status replaces it.</p><p><strong>Fallback integrity:</strong> normal browsers use deterministic policy logic but never claim WebMCP is active.</p></section></main>`;
 document.querySelector('#run')?.addEventListener('click',runSequence);document.querySelector('#approve')?.addEventListener('click',approve);document.querySelector('#reset')?.addEventListener('click',()=>location.reload());document.querySelector('#refresh-tools')?.addEventListener('click',refreshTools);document.querySelector('#tech-toggle')?.addEventListener('click',()=>document.querySelector('#tech-panel')?.classList.toggle('hidden'));
 if(webmcp)setTimeout(refreshTools,80);
}
function iframe(id){return document.querySelector(`iframe[data-id="${id}"]`)}
function postToSupplier(id,message){const frame=iframe(id);if(!frame?.contentWindow)return;frame.contentWindow.postMessage(message,new URL(supplierUrls[id],location.href).origin);}
async function call(id,action,input){if(webmcp)return executeTool(`${id}.${action}`,input,supplierUrls);return invokePolicy(id,action,input);}
async function runSequence(){if(busy||workflow!=='IDLE')return;busy=true;orchestrating=true;try{
 workflow='DISCOVERING';render();for(const id of supplierIds){const r=await call(id,'search_inventory',{sku:mission.sku,quantity:mission.quantity});market[id]={...market[id],inventory:Number(r.available),status:'discovered'};log({source:source(),tool:`${id}.search_inventory`,supplier:id,summary:`${r.available} units available; exact match confirmed.`});await delay(120)}
 workflow='QUOTING';render();for(const id of supplierIds){const q=await call(id,'request_quote',{sku:mission.sku,quantity:mission.quantity});const d=await call(id,'check_delivery',{deadline:mission.deadline});const eligible=Boolean(d.compliant);market[id]={...market[id],quote:Number(q.total),delivery:String(q.deliveryDay),eligible,status:eligible?'quoted':'rejected',rationale:eligible?'Quote is within budget and delivery deadline is feasible.':`Rejected: ${q.deliveryDay} delivery misses Friday deadline.`};log({source:source(),tool:`${id}.request_quote`,supplier:id,summary:`${money(Number(q.total))} quote; delivery ${q.deliveryDay}.`,policy:eligible?'Constraint check: PASS':'Constraint check: FAIL — deadline'});await delay(120)}
 workflow='NEGOTIATING';render();for(const id of supplierIds){const r=await call(id,'counter_offer',{desiredTotal:desiredOffers[id]});market[id]={...market[id],negotiated:Number(r.finalTotal),status:market[id].eligible===false?'rejected':'negotiated',rationale:market[id].eligible===false?market[id].rationale:`${String(r.status).toUpperCase()}: ${r.reason}`};log({source:source(),tool:`${id}.counter_offer`,supplier:id,summary:`${String(r.status).toUpperCase()} at ${money(Number(r.finalTotal))}.`,policy:String(r.reason)});await delay(140)}
 workflow='COMPARING';render();await delay(250);const winner=rankOffers(market);if(winner!=='bravo')throw new Error(`Deterministic ranking invariant failed: expected bravo, got ${winner}.`);market.alpha={...market.alpha,status:'negotiated',rationale:'Compliant, but Bravo has the lower compliant negotiated total.'};market.bravo={...market.bravo,status:'winner',rationale:'Recommended: lowest negotiated total that satisfies every mission constraint.'};market.charlie={...market.charlie,status:'rejected',rationale:'Lower price rejected because Monday delivery violates the Friday deadline.'};log({source:source(),tool:'policy.rank_offers',summary:'Bravo selected at $2,325. Charlie rejected despite lower price.',policy:'Hard constraints outrank price optimization.'});workflow='AWAITING_APPROVAL';log({source:source(),tool:'authority.gate',summary:'Execution stopped. Final financial commitment requires human approval.',policy:'Purchase capability remains unavailable.'});
 }catch(error){log({source:source(),tool:'orchestrator.error',summary:error instanceof Error?error.message:'Unknown error.'});}finally{busy=false;orchestrating=false;render();}}
async function approve(){if(busy||workflow!=='AWAITING_APPROVAL')return;busy=true;orchestrating=true;workflow='APPROVED';log({source:'Human',tool:'approval',supplier:'bravo',summary:'Approved Bravo Safety Supply at $2,325.',policy:'Approval scope: OD-APPROVED-1047'});postToSupplier('bravo',{type:'opendeal:approval',supplierId:'bravo',approved:true});await delay(220);try{const result=webmcp?await executeTool('bravo.create_purchase_order',{approvedTotal:2325,approvalToken:'OD-APPROVED-1047'},supplierUrls):{supplierId:'bravo',poId:'OD-1047',total:2325,deliveryDay:'Friday',status:'CONFIRMED'};postToSupplier('bravo',{type:'opendeal:approval',supplierId:'bravo',ordered:true});market.bravo={...market.bravo,status:'ordered',rationale:'Purchase order OD-1047 confirmed. Delivery Friday.'};log({source:source(),tool:'bravo.create_purchase_order',supplier:'bravo',summary:`PO ${result.poId} confirmed at ${money(Number(result.total))}.`,policy:'Purchase capability consumed; order-status capability becomes available.'});workflow='ORDERED';}catch(error){log({source:source(),tool:'purchase.error',supplier:'bravo',summary:error instanceof Error?error.message:'Purchase failed.'});workflow='AWAITING_APPROVAL';}finally{busy=false;orchestrating=false;render();}}
async function refreshTools(){const title=document.querySelector('#inspector-title'),list=document.querySelector('#tool-list');if(!webmcp||!title||!list)return;try{const tools=await getToolsFromSuppliers(supplierUrls);title.textContent=`${tools.length} registered tools`;list.innerHTML=tools.length?tools.map(t=>`<div class="tool-row"><span>⌘</span><code>${esc(t.name)}</code><span>${esc(t.origin??'same-origin')}</span></div>`).join(''):'<p class="muted">No tools currently exposed.</p>';}catch(error){title.textContent='Inspector error';list.innerHTML=`<p class="muted">${esc(error instanceof Error?error.message:'Unknown error')}</p>`;}}
window.addEventListener('message',(event)=>{const allowed=new Set([location.origin,...Object.values(supplierUrls).map(u=>new URL(u,location.href).origin)]);if(!allowed.has(event.origin))return;const d=event.data||{};if(d.type==='opendeal:tool-result'&&webmcp&&!orchestrating)log({source:'WebMCP',tool:d.tool,supplier:d.supplierId,summary:'Tool executed by a browser agent through the supplier context.'});});
if(webmcp&&document.modelContext){document.modelContext.addEventListener('toolchange',()=>setTimeout(refreshTools,0));}
render();
